//
// Created by 黃漢軒 on 2023/12/25.
//

#ifndef PRACTICALTOOLSFORSIMPLEDESIGN_TRANSPARENTIMAGEBASE64_HPP
#define PRACTICALTOOLSFORSIMPLEDESIGN_TRANSPARENTIMAGEBASE64_HPP

#include <string>

// A transparent image base64 string.
// Since we want to hardcode the image, we have such a long string here.
// The original image should find in here: https://i.imgur.com/zS4sPCN.png
std::string transparentImage = "iVBORw0KGgoAAAANSUhEUgAABAAAAAQAAgMAAAACc8MQ"
                               "AAAAIGNIUk0AAHomAACAhAAA+gAAAIDoAAB1MAAA6mAA"
                               "ADqYAAAXcJy6UTwAAAAJUExURf8A3AAAAP///6bxqqgA"
                               "AAABYktHRAJmC3xkAAAAB3RJTUUH5wwZBjExvHoPtAAA"
                               "CkBJREFUeNrt0bEJwEAQBDE36f5bcQkfPVrMXD4g9p7n"
                               "cO/h/t5zgO45QPccoHsO0D0H6J4DdM8BuucA3XOA7jlA"
                               "9xygew7QPQfongN0zwG65wDdc4DuOUD3HKB7DtA9B+ie"
                               "A3TPAbrnAN1zgO45QPccoHsO0D0H6J4DdM8BuucA3XOA"
                               "7jlA9xygew7QPQfongN0zwG65wDdc4DuOUD3HKB7DtA9"
                               "B+ieA3TPAbrnAN1zgO45QPccoHsO0D0H6J4DdM8BuucA"
                               "3XOA7jlA9xygew7QPQfongN0zwG65wDdc4DuOUD3HKB7"
                               "DtA9B+ieA3TPAbrnAN1zgO45QPccoHsO0D0H6J4DdM8B"
                               "uucA3XOA7jlA9xygew7QPQfongN0zwG65wDdc4DuOUD3"
                               "HKB7DtA9B+ieA3TPAbrnAN1zgO45QPccoHsO0D0H6J4D"
                               "dM8BuucA3XOA7jlA9xygew7QPQfongN0zwG65wDdc4Du"
                               "OUD3HKB7DtA9B+ieA3TPAbrnAN1zgO45QPccoHsO0D0H"
                               "6J4DdM8B1/t5YB9ugAZogAZogAZogAZogAZogAZogAZo"
                               "gAZogAZogAZogAZogAZogAZogAZogAZogAZogAZogAZo"
                               "gAZogAZogAZogAZogAZogAZogAZogAZogAZogAZogAZo"
                               "gAZogAZogHWA7jlA9xygew7QPQfongN0zwG65wDdc4Du"
                               "OUD3HKB7DtA9B+ieA3TPAbrnAN1zgO45QPccoHsO0D0H"
                               "6J4DdM8BuucA3XOA7jlA9xygew7QPQfongN0zwG65wDd"
                               "c4DuOUD3HKB7DtA9B+ieA3TPAbrnAN1zgO45QPccoHsO"
                               "0D0H6J4DdM8BuucA3XOA7jlA9xygew7QPQfongN0zwG6"
                               "5wDdc4DuOUD3HKB7DtA9B+ieA3TPAbpvoHWA7jlA9xyg"
                               "ew7QPQfongN0zwG65wDdc4DuOUD3HKB7DtA9B+ieA3TP"
                               "AbrnAN1zgO45QPccoHsO0D0H6J4DdM8BuucA3XOA7jlA"
                               "9xygew7QPQfongN0zwG65wDdc4DuOUD3HKB7DtA9B+ie"
                               "A3TPAbrnAN1zgO45QPccoHsO0D0H6J4DdM8BuucA3XOA"
                               "7jlA9xygew7QPQfongN0zwG65wDdc4DuOUD3HKB7DtA9"
                               "B+ieA3TPAbrnAN1zgO45QPccoHsO0D0H6J4DdM8BuucA"
                               "3XOA7jlA9xygew7QPQfongN0zwG65wDdc4DuOUD3HKB7"
                               "DtA9B+ieA3TPAbrnAN1zgO45QPccoHsO0D0H6J4DdM8B"
                               "uucA3XOA7jlA9xygew7QPQfongN0zwG65wDdc4DuOUD3"
                               "HKB7DtA9B+ieA3TPAbrnAN1zgO45QPccoHsO0D0H6J4D"
                               "dM8BuucA3XOA7jlA9xygew7QPQfongN0zwHX+3lgH26A"
                               "BmiABmiABmiABmiABmiABmiABmiABmiABmiABmiABmiA"
                               "BmiABmiABmiABmiABmiABmiABmiABmiABmiABmiABmiA"
                               "BmiABmiABmiABmiABmiABmiABmiABmiABmiAdYDuOUD3"
                               "HKB7DtA9B+ieA3TPAbrnAN1zgO45QPccoHsO0D0H6J4D"
                               "dM8BuucA3XOA7jlA9xygew7QPQfongN0zwG65wDdc4Du"
                               "OUD3HKB7DtA9B+ieA3TPAbrnAN1zgO45QPccoHsO0D0H"
                               "6J4DdM8BuucA3XOA7jlA9xygew7QPQfongN0zwG65wDd"
                               "c4DuOUD3HKB7DtA9B+ieA3TPAbrnAN1zgO45QPccoHsO"
                               "0D0H6J4DdM8Bum+gdYDuOUD3HKB7DtA9B+ieA3TPAbrn"
                               "AN1zgO45QPccoHsO0D0H6J4DdM8BuucA3XOA7jlA9xyg"
                               "ew7QPQfongN0zwG65wDdc4DuOUD3HKB7DtA9B+ieA3TP"
                               "AbrnAN1zgO45QPccoHsO0D0H6J4DdM8BuucA3XOA7jlA"
                               "9xygew7QPQfongN0zwG65wDdc4DuOUD3HKB7DtA9B+ie"
                               "A3TPAbrnAN1zgO45QPccoHsO0D0H6J4DdM8BuucA3XOA"
                               "7jlA9xygew7QPQfongN0zwG65wDdc4DuOUD3HKB7DtA9"
                               "B+ieA3TPAbrnAN1zgO45QPccoHsO0D0H6J4DdM8BuucA"
                               "3XOA7jlA9xygew7QPQfongN0zwG65wDdc4DuOUD3HKB7"
                               "DtA9B+ieA3TPAbrnAN1zgO45QPccoHsO0D0H6J4DdM8B"
                               "uucA3XOA7jlA9xygew7QPQfongN0zwG65wDdc4DuOUD3"
                               "HKB7DtA9B+ieA3TPAdf7eWAfboAGaIAGaIAGaIAGaIAG"
                               "aIAGaIAGaIAGaIAGaIAGaIAGaIAGaIAGaIAGaIAGaIAG"
                               "aIAGaIAGaIAGaIAGaIAGaIAGaIAGaIAGaIAGaIAGaIAG"
                               "aIAGaIAGaIAGaIAGaIB1gO45QPccoHsO0D0H6J4DdM8B"
                               "uucA3XOA7jlA9xygew7QPQfongN0zwG65wDdc4DuOUD3"
                               "HKB7DtA9B+ieA3TPAbrnAN1zgO45QPccoHsO0D0H6J4D"
                               "dM8BuucA3XOA7jlA9xygew7QPQfongN0zwG65wDdc4Du"
                               "OUD3HKB7DtA9B+ieA3TPAbrnAN1zgO45QPccoHsO0D0H"
                               "6J4DdM8BuucA3XOA7jlA9xygew7QPQfongN0zwG6b6B1"
                               "gO45QPccoHsO0D0H6J4DdM8BuucA3XOA7jlA9xygew7Q"
                               "PQfongN0zwG65wDdc4DuOUD3HKB7DtA9B+ieA3TPAbrn"
                               "AN1zgO45QPccoHsO0D0H6J4DdM8BuucA3XOA7jlA9xyg"
                               "ew7QPQfongN0zwG65wDdc4DuOUD3HKB7DtA9B+ieA3TP"
                               "AbrnAN1zgO45QPccoHsO0D0H6J4DdM8BuucA3XOA7jlA"
                               "9xygew7QPQfongN0zwG65wDdc4DuOUD3HKB7DtA9B+ie"
                               "A3TPAbrnAN1zgO45QPccoHsO0D0H6J4DdM8BuucA3XOA"
                               "7jlA9xygew7QPQfongN0zwG65wDdc4DuOUD3HKB7DtA9"
                               "B+ieA3TPAbrnAN1zgO45QPccoHsO0D0H6J4DdM8BuucA"
                               "3XOA7jlA9xygew7QPQfongN0zwG65wDdc4DuOUD3HKB7"
                               "DtA9B+ieA3TPAbrnAN1zgO45QPccoHsO0D0H6J4DdM8B"
                               "1/t5YB9ugAZogAZogAZogAZogAZogAZogAZogAZogAZo"
                               "gAZogAZogAZogAZogAZogAZogAZogAZogAZogAZogAZo"
                               "gAZogAZogAZogAZogAZogAZogAZogAZogAZogAZogAZo"
                               "gHWA7jlA9xygew7QPQfongN0zwG65wDdc4DuOUD3HKB7"
                               "DtA9B+ieA3TPAbrnAN1zgO45QPccoHsO0D0H6J4DdM8B"
                               "uucA3XOA7jlA9xygew7QPQfongN0zwG65wDdc4DuOUD3"
                               "HKB7DtA9B+ieA3TPAbrnAN1zgO45QPccoHsO0D0H6J4D"
                               "dM8BuucA3XOA7jlA9xygew7QPQfongN0zwG65wDdc4Du"
                               "OUD3HKB7DtA9B+ieA3TPAbr/ABxLCfesmysEAAAAJXRF"
                               "WHRkYXRlOmNyZWF0ZQAyMDIzLTEyLTI1VDA2OjQ5OjQ4"
                               "KzAwOjAw0d583AAAACV0RVh0ZGF0ZTptb2RpZnkAMjAy"
                               "My0xMi0yNVQwNjo0OTo0OCswMDowMKCDxGAAAAAodEVY"
                               "dGRhdGU6dGltZXN0YW1wADIwMjMtMTItMjVUMDY6NDk6"
                               "NDkrMDA6MDBR4e4LAAAAAElFTkSuQmCC";

#endif // PRACTICALTOOLSFORSIMPLEDESIGN_TRANSPARENTIMAGEBASE64_HPP
